name: Deploy to SEOhost via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          # wysyłamy tylko pliki strony
          local_path: "./"

          # katalog public_html na serwerze
          remote_path: ${{ secrets.REMOTE_PATH }}

          delete_remote_files: false

          # wykluczamy wszystko, czego nie chcemy na serwerze
          exclude: |
            .git
            .github
            README.md
            .gitignore
            node_modules
            *.md
